# MySQL
development:
  adapter: mysql2
  encoding: utf8
  database: campusApp_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

# TODO: configure 'test' database
test:
  adapter: mysql2
  database: test
  username: root
  password:
  encoding: utf8