# MySQL
development:
  adapter: mysql2
  encoding: utf8
  database: campusApp_development
  pool: 5
  username: root
  password: campusu
  socket: /tmp/mysql.sock

# Test
test:
  adapter: mysql2
  encoding: utf8
  database: test
  username: root
  password: campusu
